---
- hosts: all
  remote_user: vagrant
  sudo: true

  pre_tasks:
    - copy: src=~/.aliases dest=~/.aliases
    - copy: src=~/.zshrc dest=~/.zshrc
    - copy: src=~/.tmux.conf dest=~/.tmux.conf
    - copy: src=~/.gitattributes dest=~/.gitattributes
    - copy: src=~/.gitconfig dest=~/.gitconfig
    - copy: src=~/.gitignore dest=~/.gitignore
    - command: sed -i 's/us.archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list
    - command: sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list
    - command: sed -i 's/mirror.rackspace.com/free.nchc.org.tw/g' /etc/apt/sources.list

  vars:
    apt_upgrade: false
    apt_install: [language-pack-zh-hant, vim, curl, wget, htop, tree, ntp, tmux, zsh, build-essential, libssl-dev, libffi-dev, python-dev]
    user: vagrant

    docker_compose_version: 1.4.2
    # etcd_version: v2.1.2
    # etcd_platform: linux
    # etcd_arch: amd64
    # etcd_release: "etcd-{{ etcd_version }}-{{ etcd_platform }}-{{ etcd_arch }}"
    # etcd_download_url: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/{{ etcd_release }}.tar.gz"
    # etcd_download_dir: /usr/local/src
    # etcd_dir: /usr/local/sbin
    # etcd_data_dir: /var/cache/etcd/state
    # etcd_cmd: "{{ etcd_dir }}/etcd"

  roles:
    - apt
    # - docker
    - git
    # - ohmyzsh
#    - etcd

  tasks:
    - name: ensure ntpd is at the latest version
      apt: name=ntp state=latest
      notify:
      - restart ntpd

    - name: install latest docker
      shell: wget -qO- https://get.docker.com/ | sh
      notify:
      - add user to docker group

    - name: install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      sudo: false

    # - name: copy my alias
    #   copy: src=.aliases dest=~/.aliases

    # - name: copy my zsh setting
    #   copy: src=.zshrc dest=~/.zshrc

    # - name: copy my tmux setting
    #   copy: src=.tmux.conf dest=/home/vagrant/.tmux.conf

    # - name: create .oh-my-zsh theme dir
    #   shell: mkdir -p ~/.oh-my-zsh/themes

    - name: copy my zsh theme setting
      copy: src=metavige-agnoster.zsh-theme dest=/home/vagrant/.oh-my-zsh/themes/metavige-agnoster.zsh-theme

    - name: download docker-compose
      get_url: url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
      notify:
      - make execution docker-compose

    # - name: download etcd
    #   get_url: url={{ etcd_download_url }} dest={{ etcd_download_dir }}/etcd.zip

    # - name: unarchive etcd
    #   unarchive: copy=no
    #     src={{ etcd_download_dir }}/etcd.zip
    #     dest={{ etcd_download_dir }}

    # - name: copy binaries from archive into etcd dir
    #   shell: rsync -auv {{ etcd_download_dir }}/{{ etcd_release }}/{{ item }} {{ etcd_dir }}
    #   with_items:
    #     - etcd
    #     - etcdctl

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

    - name: add user to docker group
      shell: usermod -aG docker vagrant

    - name: make execution docker-compose
      shell: chmod +x /usr/local/bin/docker-compose
