---
- src: kosssi.apt
  name: apt
  path: roles/
  
- src: amidos.install-docker
  name: docker
  path: roles/
   
- src: geerlingguy.git
  name: git
  path: roles/

- src: devbox.oh-my-zsh
  name: ohmyzsh
  path: roles/
  
- src: retr0h.etcd
  name: etcd
  path: roles/