---
- name: download etcd
  get_url: url={{ etcd_download_url }} dest={{ etcd_download_dir }}/etcd.zip

- name: unarchive etcd
  unarchive: copy=no
             src={{ etcd_download_dir }}/etcd.zip
             dest={{ etcd_download_dir }}

# TODO(retr0h): Sucks the `copy` module doesn't do this.
#               We get idempotency from `rsync(1)`.
- name: copy binaries from archive into etcd dir
  shell: rsync -auv {{ etcd_download_dir }}/{{ etcd_release }}/{{ item }} {{ etcd_dir }}
  with_items:
    - etcd
    - etcdctl

- name: etcd upstart service
  template: src=etc/init/etcd.conf.j2 dest=/etc/init/etcd.conf
  notify:
    - restart etcd
